name: cd
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build Static
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: rm -rf node_modules/.cache && next build && next export && touch out/.nojekyll
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      - name: Deploy
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out 
