name: ci
on: 
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install --frozen-lockfile
      - run: yarn publish:gh-pages
